services:
    org_structure_db:
        image: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s

    org_structure_service:
        build: .
        env_file:
            - .env
        ports:
            - "8000:8000"

        depends_on:
            org_structure_db:
                condition: service_healthy
