# Для тестирования отдельного сервиса
services:
    auth_db:
        image: postgres
        ports:
            - "5432:5432"
        env_file:
            - ./.env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 5s

    auth_service:
        build: .
        env_file:
            - ./.env
        ports:
            - "8002:8000"

        depends_on:
            auth_db:
                condition: service_healthy
