"""Add fields(start_time, start_time) in Task

Revision ID: fb9a6acc494b
Revises: f3ec8be4ceec
Create Date: 2025-04-17 16:33:30.140327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb9a6acc494b'
down_revision: Union[str, None] = 'f3ec8be4ceec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('tasks', sa.Column('end_time', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'end_time')
    op.drop_column('tasks', 'start_time')
    # ### end Alembic commands ###
