"""Add cascade

Revision ID: ebb5a316f31c
Revises: e508aad6271a
Create Date: 2025-04-19 10:12:23.099828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb5a316f31c'
down_revision: Union[str, None] = 'e508aad6271a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('team_employee_team_id_fkey', 'team_employee', type_='foreignkey')
    op.create_foreign_key(None, 'team_employee', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('team_news_team_id_fkey', 'team_news', type_='foreignkey')
    op.create_foreign_key(None, 'team_news', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_news', type_='foreignkey')
    op.create_foreign_key('team_news_team_id_fkey', 'team_news', 'teams', ['team_id'], ['id'])
    op.drop_constraint(None, 'team_employee', type_='foreignkey')
    op.create_foreign_key('team_employee_team_id_fkey', 'team_employee', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###
