"""Change role to position in EmployeeStructure

Revision ID: 4af35bb6cf2a
Revises: 5aec1bbcb4c2
Create Date: 2025-04-15 08:00:59.934946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4af35bb6cf2a'
down_revision: Union[str, None] = '5aec1bbcb4c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_structure', sa.Column('position', sa.String(length=255), nullable=False))
    op.drop_column('employee_structure', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_structure', sa.Column('role', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('employee_structure', 'position')
    # ### end Alembic commands ###
