"""Initial revision

Revision ID: 5aec1bbcb4c2
Revises: 
Create Date: 2025-04-11 16:29:57.670712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aec1bbcb4c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_structure',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('structure_type', sa.Enum('LINEAR', 'FUNCTIONAL', 'MATRIX', 'DIVISIONAL', 'LINEAR_FUNCTIONAL', name='structuretype', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team_structure.team_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'name', name='uq_division_team_name')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team_structure.team_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_structure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'department_id', name='uq_employee_department')
    )
    op.create_table('employee_managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_structure_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employee_structure_id'], ['employee_structure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_managers')
    op.drop_table('employee_structure')
    op.drop_table('departments')
    op.drop_table('divisions')
    op.drop_table('team_structure')
    # ### end Alembic commands ###
